// frontend/src/components/DiscussionsList.tsx
import React, { useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ActivityIndicator,
  FlatList,
  RefreshControl,
  ScrollView,
} from "react-native";
import { useNavigation } from "@react-navigation/native";
import { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { MainStackParamList } from "../../Navigator";
import { Ionicons } from "@expo/vector-icons";
import Feather from "@expo/vector-icons/Feather";
import { useInfiniteQuery } from "@tanstack/react-query";
import DiscussionListSkeleton from "../skeletons/DiscussionListSkeleton";

const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL;

type NavigationProp = NativeStackNavigationProp<MainStackParamList>;

interface Discussion {
  id: string;
  title: string;
  description: string;
  discussion_type: "topic" | "community";
  topic_id?: string;
  category?: string;
  tags: string[];
  username: string;
  reply_count: number;
  upvote_count: number;
  created_at: string;
  time_ago: string;
  is_auto_created: boolean;
}

interface DiscussionsListProps {
  category?: string;
  discussionType?: "topic" | "community";
  onCreatePress?: () => void;
}

const PAGE_LIMIT = 20;

const fetchDiscussions = async ({ pageParam, queryKey }: any) => {
  const [_, category, discussionType, sortBy] = queryKey;
  
  const params = new URLSearchParams();
  if (category) params.append("category", category);
  if (discussionType) params.append("discussion_type", discussionType);
  params.append("sort_by", sortBy);
  params.append("limit", PAGE_LIMIT.toString());
  params.append("skip", (pageParam * PAGE_LIMIT).toString());

  const response = await fetch(`${API_BASE_URL}/discussions?${params.toString()}`);
  if (!response.ok) throw new Error('Network response was not ok');
  
  const data = await response.json();
  return data.discussions || [];
};

const getCategoryColor = (category?: string): string => {
  if (!category) return "#6B7280";
  switch (category.toLowerCase()) {
    case "technology":
    case "tech": return "#f16365ff";
    case "finance": return "#73aef2ff";
    case "politics": return "#8B5CF6";
    default: return "#6B7280";
  }
};

const DiscussionsList: React.FC<DiscussionsListProps> = ({
  category,
  discussionType,
  onCreatePress,
}) => {
  const navigation = useNavigation<NavigationProp>();
  const [sortBy, setSortBy] = useState<"latest" | "most_discussed">("latest");

  const {
    data,
    isLoading,
    isRefetching,
    fetchNextPage,
    hasNextPage,
    isFetchingNextPage,
    refetch
  } = useInfiniteQuery({
    queryKey: ['discussions', category, discussionType, sortBy],
    queryFn: fetchDiscussions,
    initialPageParam: 0,
    getNextPageParam: (lastPage, allPages) => {
      return lastPage.length === PAGE_LIMIT ? allPages.length : undefined;
    },
    staleTime: 1000 * 60 * 2, 
  });

  const discussions = data?.pages.flat() || [];

  const getTypeStyles = (type: string, categoryName?: string) => {
    const categoryColor = getCategoryColor(categoryName);
    if (type === "topic") {
      return {
        bg: "white",
        text: categoryColor,
        icon: "chatbubble-ellipses-outline" as const,
        label: "Podnova Topic Discussion",
      };
    } else {
      return {
        bg: "#FEF3C7",
        text: "#d68b0a",
        icon: "people-outline" as const,
        label: "Community Discussion",
      };
    }
  };

  // HELPER FOR PILL STYLES (Matching TopicsList)
  const getSortButtonStyle = (option: string) => [
    styles.sortPill,
    sortBy === option && styles.sortPillActive
  ];

  const getSortTextStyle = (option: string) => [
    styles.sortPillText,
    sortBy === option && styles.sortPillTextActive
  ];

  const renderItem = ({ item: discussion }: { item: Discussion }) => {
    const typeStyles = getTypeStyles(discussion.discussion_type, discussion.category);
    const categoryColor = getCategoryColor(discussion.category);
    const isAutoGenerated = discussion.discussion_type === "topic";
    const cardStyle = isAutoGenerated ? styles.discussionCard : [styles.discussionCard, styles.communityCard];

    return (
      <TouchableOpacity
        style={cardStyle}
        onPress={() => navigation.navigate("DiscussionDetail", { discussionId: discussion.id })}
        activeOpacity={0.7}
      >
        <View style={styles.discussionHeader}>
          <View style={styles.headerLeft}>
            <View style={[styles.typeBadge, { backgroundColor: typeStyles.bg }]}>
              <Ionicons name={typeStyles.icon} size={10} color={typeStyles.text} />
              <Text style={[styles.typeBadgeText, { color: typeStyles.text }]}>
                {typeStyles.label}
              </Text>
            </View>
            {discussion.category && (
              <View style={styles.miniCategoryBadge}>
                <Text style={[styles.miniCategoryText, { color: categoryColor }]}>
                  {discussion.category}
                </Text>
              </View>
            )}
          </View>

          <View style={styles.metaInfo}>
            <Ionicons name="chatbubble-outline" size={11} color="#6B7280" />
            <Text style={styles.metaText}>{discussion.reply_count}</Text>
            <Feather name="thumbs-up" size={11} color="#6B7280" style={styles.metaIcon} />
            <Text style={styles.metaText}>{discussion.upvote_count}</Text>
          </View>
        </View>

        <Text style={styles.discussionTitle} numberOfLines={2}>
          {discussion.title}
        </Text>
        <Text style={styles.discussionDescription} numberOfLines={2}>
          {discussion.description}
        </Text>

        <View style={styles.discussionFooter}>
          <View style={styles.footerLeft}>
            <Ionicons name="person-circle-outline" size={16} color="#9CA3AF" />
            <Text style={styles.footerText}>{discussion.username}</Text>
          </View>
          <Text style={styles.footerText}>{discussion.time_ago}</Text>
        </View>

        {discussion.tags && discussion.tags.length > 0 && (
          <View style={styles.tagsRow}>
            {discussion.tags.slice(0, 3).map((tag, index) => (
              <View key={index} style={styles.tag}>
                <Text style={styles.tagText}>#{tag}</Text>
              </View>
            ))}
          </View>
        )}
      </TouchableOpacity>
    );
  };

  const renderFooter = () => {
    if (!isFetchingNextPage) return <View style={{ height: 40 }} />;
    return (
      <View style={styles.footerLoader}>
        <ActivityIndicator size="small" color="#6366F1" />
      </View>
    );
  };

  const renderEmptyComponent = () => {
    if (isLoading) return null;
    return (
      <View style={styles.emptyState}>
        <Ionicons name="chatbubbles-outline" size={64} color="#D1D5DB" />
        <Text style={styles.emptyTitle}>No Discussions Yet</Text>
        <Text style={styles.emptyText}>
          {category
            ? `Be the first to start a discussion in ${category}`
            : "Start a discussion to connect with the community"}
        </Text>
        {onCreatePress && (
          <TouchableOpacity style={styles.emptyButton} onPress={onCreatePress}>
            <Text style={styles.emptyButtonText}>Start Discussion</Text>
          </TouchableOpacity>
        )}
      </View>
    );
  };

  if (isLoading && discussions.length === 0) {
    return <DiscussionListSkeleton />;
  }

  return (
    <View style={styles.container}>
      {/* REDESIGNED HEADER BAR */}
      <View style={styles.actionsBar}>
        <ScrollView 
          horizontal 
          showsHorizontalScrollIndicator={false} 
          contentContainerStyle={styles.sortScroll}
          style={styles.scrollWrapper}
        >
          <TouchableOpacity style={getSortButtonStyle("latest")} onPress={() => setSortBy("latest")}>
            <Text style={getSortTextStyle("latest")}>Latest</Text>
          </TouchableOpacity>
          <TouchableOpacity style={getSortButtonStyle("most_discussed")} onPress={() => setSortBy("most_discussed")}>
            <Text style={getSortTextStyle("most_discussed")}>Most Discussed</Text>
          </TouchableOpacity>
        </ScrollView>

        {onCreatePress && (
          <TouchableOpacity style={styles.createButton} onPress={onCreatePress}>
            <Ionicons name="add" size={20} color="#d68b0a" />
            <Text style={styles.createButtonText}>New</Text>
          </TouchableOpacity>
        )}
      </View>

      <FlatList
        data={discussions}
        keyExtractor={(item) => item.id}
        renderItem={renderItem}
        style={styles.list}
        contentContainerStyle={styles.listContent}
        showsVerticalScrollIndicator={false}
        ListEmptyComponent={renderEmptyComponent}
        ListFooterComponent={renderFooter}
        onEndReached={() => {
          if (hasNextPage && !isFetchingNextPage) fetchNextPage();
        }}
        onEndReachedThreshold={0.5}
        refreshControl={
          <RefreshControl 
            refreshing={isRefetching && !isFetchingNextPage} 
            onRefresh={refetch} 
          />
        }
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 60,
  },
  
  // MATCHED FILTER DESIGN
  actionsBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    backgroundColor: "transparent",
  },
  scrollWrapper: {
    flex: 1,
    marginRight: 10,
  },
  sortScroll: {
    gap: 8,
  },
  sortPill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "transparent",
  },
  sortPillActive: {
    backgroundColor: "#EEF2FF",
    borderColor: "#C7D2FE",
  },
  sortPillText: {
    fontSize: 13,
    fontWeight: "500",
    color: "#4B5563",
  },
  sortPillTextActive: {
    color: "#4F46E5",
    fontWeight: "600",
  },

  createButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderColor: "#d68b0a",
    borderWidth: 1,
    backgroundColor: "#FEF3C7",
    gap: 4,
  },
  createButtonText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#d68b0a",
  },
  
  list: {
    flex: 1,
    backgroundColor: "transparent",
  },
  listContent: {
    paddingBottom: 20,
  },
  discussionCard: {
    backgroundColor: "#FFFFFF",
    marginBottom: 12,
    padding: 14,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  communityCard: {
    borderLeftWidth: 4,
    borderLeftColor: "#F59E0B",
  },
  discussionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  typeBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    gap: 4,
  },
  typeBadgeText: {
    fontSize: 11,
    fontWeight: "600",
  },
  miniCategoryBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  miniCategoryText: {
    fontSize: 10,
    fontWeight: "500",
    textTransform: "capitalize",
  },
  metaInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  metaIcon: {
    marginLeft: 8,
  },
  metaText: {
    fontSize: 11,
    color: "#6B7280",
    marginLeft: 2,
  },
  discussionTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#111827",
    lineHeight: 20,
    marginBottom: 4,
  },
  discussionDescription: {
    fontSize: 13,
    color: "#6B7280",
    lineHeight: 18,
    marginBottom: 8,
  },
  discussionFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  footerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  footerText: {
    fontSize: 11,
    color: "#9CA3AF",
  },
  tagsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  tag: {
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  tagText: {
    fontSize: 10,
    color: "#6366F1",
    fontWeight: "500",
  },
  footerLoader: {
    paddingVertical: 20,
  },
  emptyState: {
    paddingTop: 80,
    paddingHorizontal: 40,
    alignItems: "center",
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#111827",
    marginTop: 16,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 14,
    color: "#6B7280",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 24,
  },
  emptyButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: "#6366F1",
  },
  emptyButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#FFFFFF",
  },
});

export default DiscussionsList;